// Because enums cannot be nested within other types, they must all be hoisted

declare const enum command_node_extraNodeData_properties {
    "SINGLE_WORD" = 0,
    "QUOTABLE_PHRASE" = 1,
    "GREEDY_PHRASE" = 2,
}

declare const enum packet_name {
}

declare const enum packet_name_2 {
    "set_protocol" = 0x00,
    "legacy_server_list_ping" = 0xfe,
}

declare const enum packet_name_3 {
    "server_info" = 0x00,
    "ping" = 0x01,
}

declare const enum packet_name_4 {
    "ping_start" = 0x00,
    "ping" = 0x01,
}

declare const enum packet_name_5 {
    "disconnect" = 0x00,
    "encryption_begin" = 0x01,
    "success" = 0x02,
    "compress" = 0x03,
    "login_plugin_request" = 0x04,
}

declare const enum packet_name_6 {
    "login_start" = 0x00,
    "encryption_begin" = 0x01,
    "login_plugin_response" = 0x02,
}

declare const enum packet_player_info_action {
    "add_player" = 0,
    "update_game_mode" = 1,
    "update_latency" = 2,
    "update_display_name" = 3,
    "remove_player" = 4,
}

declare const enum packet_name_7 {
    "spawn_entity" = 0x00,
    "spawn_entity_experience_orb" = 0x01,
    "spawn_entity_weather" = 0x02,
    "spawn_entity_living" = 0x03,
    "spawn_entity_painting" = 0x04,
    "named_entity_spawn" = 0x05,
    "animation" = 0x06,
    "statistics" = 0x07,
    "block_break_animation" = 0x08,
    "tile_entity_data" = 0x09,
    "block_action" = 0x0a,
    "block_change" = 0x0b,
    "boss_bar" = 0x0c,
    "difficulty" = 0x0d,
    "chat" = 0x0e,
    "multi_block_change" = 0x0f,
    "tab_complete" = 0x10,
    "declare_commands" = 0x11,
    "transaction" = 0x12,
    "close_window" = 0x13,
    "open_window" = 0x14,
    "window_items" = 0x15,
    "craft_progress_bar" = 0x16,
    "set_slot" = 0x17,
    "set_cooldown" = 0x18,
    "custom_payload" = 0x19,
    "named_sound_effect" = 0x1a,
    "kick_disconnect" = 0x1b,
    "entity_status" = 0x1c,
    "nbt_query_response" = 0x1d,
    "explosion" = 0x1e,
    "unload_chunk" = 0x1f,
    "game_state_change" = 0x20,
    "keep_alive" = 0x21,
    "map_chunk" = 0x22,
    "world_event" = 0x23,
    "world_particles" = 0x24,
    "login" = 0x25,
    "map" = 0x26,
    "entity" = 0x27,
    "rel_entity_move" = 0x28,
    "entity_move_look" = 0x29,
    "entity_look" = 0x2a,
    "vehicle_move" = 0x2b,
    "open_sign_entity" = 0x2c,
    "craft_recipe_response" = 0x2d,
    "abilities" = 0x2e,
    "combat_event" = 0x2f,
    "player_info" = 0x30,
    "face_player" = 0x31,
    "position" = 0x32,
    "bed" = 0x33,
    "unlock_recipes" = 0x34,
    "entity_destroy" = 0x35,
    "remove_entity_effect" = 0x36,
    "resource_pack_send" = 0x37,
    "respawn" = 0x38,
    "entity_head_rotation" = 0x39,
    "select_advancement_tab" = 0x3a,
    "world_border" = 0x3b,
    "camera" = 0x3c,
    "held_item_slot" = 0x3d,
    "scoreboard_display_objective" = 0x3e,
    "entity_metadata" = 0x3f,
    "attach_entity" = 0x40,
    "entity_velocity" = 0x41,
    "entity_equipment" = 0x42,
    "experience" = 0x43,
    "update_health" = 0x44,
    "scoreboard_objective" = 0x45,
    "set_passengers" = 0x46,
    "teams" = 0x47,
    "scoreboard_score" = 0x48,
    "spawn_position" = 0x49,
    "update_time" = 0x4a,
    "title" = 0x4b,
    "stop_sound" = 0x4c,
    "sound_effect" = 0x4d,
    "playerlist_header" = 0x4e,
    "collect" = 0x4f,
    "entity_teleport" = 0x50,
    "advancements" = 0x51,
    "entity_update_attributes" = 0x52,
    "entity_effect" = 0x53,
    "declare_recipes" = 0x54,
    "tags" = 0x55,
}

declare const enum packet_name_8 {
    "teleport_confirm" = 0x00,
    "query_block_nbt" = 0x01,
    "chat" = 0x02,
    "client_command" = 0x03,
    "settings" = 0x04,
    "tab_complete" = 0x05,
    "transaction" = 0x06,
    "enchant_item" = 0x07,
    "window_click" = 0x08,
    "close_window" = 0x09,
    "custom_payload" = 0x0a,
    "edit_book" = 0x0b,
    "query_entity_nbt" = 0x0c,
    "use_entity" = 0x0d,
    "keep_alive" = 0x0e,
    "flying" = 0x0f,
    "position" = 0x10,
    "position_look" = 0x11,
    "look" = 0x12,
    "vehicle_move" = 0x13,
    "steer_boat" = 0x14,
    "pick_item" = 0x15,
    "craft_recipe_request" = 0x16,
    "abilities" = 0x17,
    "block_dig" = 0x18,
    "entity_action" = 0x19,
    "steer_vehicle" = 0x1a,
    "crafting_book_data" = 0x1b,
    "name_item" = 0x1c,
    "resource_pack_receive" = 0x1d,
    "advancement_tab" = 0x1e,
    "select_trade" = 0x1f,
    "set_beacon_effect" = 0x20,
    "held_item_slot" = 0x21,
    "update_command_block" = 0x22,
    "update_command_block_minecart" = 0x23,
    "set_creative_slot" = 0x24,
    "update_structure_block" = 0x25,
    "update_sign" = 0x26,
    "arm_animation" = 0x27,
    "spectate" = 0x28,
    "block_place" = 0x29,
    "use_item" = 0x2a,
}

