// Because enums cannot be nested within other types, they must all be hoisted

declare const enum a2_parser {
    "brigadier:bool" = 0,
    "brigadier:float" = 1,
    "brigadier:double" = 2,
    "brigadier:integer" = 3,
    "brigadier:long" = 4,
    "brigadier:string" = 5,
    "minecraft:entity" = 6,
    "minecraft:game_profile" = 7,
    "minecraft:block_pos" = 8,
    "minecraft:column_pos" = 9,
    "minecraft:vec3" = 10,
    "minecraft:vec2" = 11,
    "minecraft:block_state" = 12,
    "minecraft:block_predicate" = 13,
    "minecraft:item_stack" = 14,
    "minecraft:item_predicate" = 15,
    "minecraft:color" = 16,
    "minecraft:component" = 17,
    "minecraft:message" = 18,
    "minecraft:nbt" = 19,
    "minecraft:nbt_tag" = 20,
    "minecraft:nbt_path" = 21,
    "minecraft:objective" = 22,
    "minecraft:objective_criteria" = 23,
    "minecraft:operation" = 24,
    "minecraft:particle" = 25,
    "minecraft:angle" = 26,
    "minecraft:rotation" = 27,
    "minecraft:scoreboard_slot" = 28,
    "minecraft:score_holder" = 29,
    "minecraft:swizzle" = 30,
    "minecraft:team" = 31,
    "minecraft:item_slot" = 32,
    "minecraft:resource_location" = 33,
    "minecraft:mob_effect" = 34,
    "minecraft:function" = 35,
    "minecraft:entity_anchor" = 36,
    "minecraft:int_range" = 37,
    "minecraft:float_range" = 38,
    "minecraft:item_enchantment" = 39,
    "minecraft:entity_summon" = 40,
    "minecraft:dimension" = 41,
    "minecraft:time" = 42,
    "minecraft:resource_or_tag" = 43,
    "minecraft:resource" = 44,
    "minecraft:template_mirror" = 45,
    "minecraft:template_rotation" = 46,
    "minecraft:uuid" = 47,
}

declare const enum packet_name {
}

declare const enum packet_name_2 {
    "set_protocol" = 0x00,
    "legacy_server_list_ping" = 0xfe,
}

declare const enum packet_name_3 {
    "server_info" = 0x00,
    "ping" = 0x01,
}

declare const enum packet_name_4 {
    "ping_start" = 0x00,
    "ping" = 0x01,
}

declare const enum packet_name_5 {
    "disconnect" = 0x00,
    "encryption_begin" = 0x01,
    "success" = 0x02,
    "compress" = 0x03,
    "login_plugin_request" = 0x04,
}

declare const enum packet_name_6 {
    "login_start" = 0x00,
    "encryption_begin" = 0x01,
    "login_plugin_response" = 0x02,
}

declare const enum packet_player_info_action {
    "add_player" = 0,
    "update_game_mode" = 1,
    "update_latency" = 2,
    "update_display_name" = 3,
    "remove_player" = 4,
}

declare const enum packet_name_7 {
    "spawn_entity" = 0x00,
    "spawn_entity_experience_orb" = 0x01,
    "named_entity_spawn" = 0x02,
    "animation" = 0x03,
    "statistics" = 0x04,
    "acknowledge_player_digging" = 0x05,
    "block_break_animation" = 0x06,
    "tile_entity_data" = 0x07,
    "block_action" = 0x08,
    "block_change" = 0x09,
    "boss_bar" = 0x0a,
    "difficulty" = 0x0b,
    "chat_preview" = 0x0c,
    "clear_titles" = 0x0d,
    "tab_complete" = 0x0e,
    "declare_commands" = 0x0f,
    "close_window" = 0x10,
    "window_items" = 0x11,
    "craft_progress_bar" = 0x12,
    "set_slot" = 0x13,
    "set_cooldown" = 0x14,
    "chat_suggestions" = 0x15,
    "custom_payload" = 0x16,
    "named_sound_effect" = 0x17,
    "hide_message" = 0x18,
    "kick_disconnect" = 0x19,
    "entity_status" = 0x1a,
    "explosion" = 0x1b,
    "unload_chunk" = 0x1c,
    "game_state_change" = 0x1d,
    "open_horse_window" = 0x1e,
    "initialize_world_border" = 0x1f,
    "keep_alive" = 0x20,
    "map_chunk" = 0x21,
    "world_event" = 0x22,
    "world_particles" = 0x23,
    "update_light" = 0x24,
    "login" = 0x25,
    "map" = 0x26,
    "trade_list" = 0x27,
    "rel_entity_move" = 0x28,
    "entity_move_look" = 0x29,
    "entity_look" = 0x2a,
    "vehicle_move" = 0x2b,
    "open_book" = 0x2c,
    "open_window" = 0x2d,
    "open_sign_entity" = 0x2e,
    "ping" = 0x2f,
    "craft_recipe_response" = 0x30,
    "abilities" = 0x31,
    "message_header" = 0x32,
    "player_chat" = 0x33,
    "end_combat_event" = 0x34,
    "enter_combat_event" = 0x35,
    "death_combat_event" = 0x36,
    "player_info" = 0x37,
    "face_player" = 0x38,
    "position" = 0x39,
    "unlock_recipes" = 0x3a,
    "entity_destroy" = 0x3b,
    "remove_entity_effect" = 0x3c,
    "resource_pack_send" = 0x3d,
    "respawn" = 0x3e,
    "entity_head_rotation" = 0x3f,
    "multi_block_change" = 0x40,
    "select_advancement_tab" = 0x41,
    "server_data" = 0x42,
    "action_bar" = 0x43,
    "world_border_center" = 0x44,
    "world_border_lerp_size" = 0x45,
    "world_border_size" = 0x46,
    "world_border_warning_delay" = 0x47,
    "world_border_warning_reach" = 0x48,
    "camera" = 0x49,
    "held_item_slot" = 0x4a,
    "update_view_position" = 0x4b,
    "update_view_distance" = 0x4c,
    "spawn_position" = 0x4d,
    "should_display_chat_preview" = 0x4e,
    "scoreboard_display_objective" = 0x4f,
    "entity_metadata" = 0x50,
    "attach_entity" = 0x51,
    "entity_velocity" = 0x52,
    "entity_equipment" = 0x53,
    "experience" = 0x54,
    "update_health" = 0x55,
    "scoreboard_objective" = 0x56,
    "set_passengers" = 0x57,
    "teams" = 0x58,
    "scoreboard_score" = 0x59,
    "simulation_distance" = 0x5a,
    "set_title_subtitle" = 0x5b,
    "update_time" = 0x5c,
    "set_title_text" = 0x5d,
    "set_title_time" = 0x5e,
    "entity_sound_effect" = 0x5f,
    "sound_effect" = 0x60,
    "stop_sound" = 0x61,
    "system_chat" = 0x62,
    "playerlist_header" = 0x63,
    "nbt_query_response" = 0x64,
    "collect" = 0x65,
    "entity_teleport" = 0x66,
    "advancements" = 0x67,
    "entity_update_attributes" = 0x68,
    "entity_effect" = 0x69,
    "declare_recipes" = 0x6a,
    "tags" = 0x6b,
}

declare const enum packet_name_8 {
    "teleport_confirm" = 0x00,
    "query_block_nbt" = 0x01,
    "set_difficulty" = 0x02,
    "message_acknowledgement" = 0x03,
    "chat_command" = 0x04,
    "chat_message" = 0x05,
    "chat_preview" = 0x06,
    "client_command" = 0x07,
    "settings" = 0x08,
    "tab_complete" = 0x09,
    "enchant_item" = 0x0a,
    "window_click" = 0x0b,
    "close_window" = 0x0c,
    "custom_payload" = 0x0d,
    "edit_book" = 0x0e,
    "query_entity_nbt" = 0x0f,
    "use_entity" = 0x10,
    "generate_structure" = 0x11,
    "keep_alive" = 0x12,
    "lock_difficulty" = 0x13,
    "position" = 0x14,
    "position_look" = 0x15,
    "look" = 0x16,
    "flying" = 0x17,
    "vehicle_move" = 0x18,
    "steer_boat" = 0x19,
    "pick_item" = 0x1a,
    "craft_recipe_request" = 0x1b,
    "abilities" = 0x1c,
    "block_dig" = 0x1d,
    "entity_action" = 0x1e,
    "steer_vehicle" = 0x1f,
    "pong" = 0x20,
    "recipe_book" = 0x21,
    "displayed_recipe" = 0x22,
    "name_item" = 0x23,
    "resource_pack_receive" = 0x24,
    "advancement_tab" = 0x25,
    "select_trade" = 0x26,
    "set_beacon_effect" = 0x27,
    "held_item_slot" = 0x28,
    "update_command_block" = 0x29,
    "update_command_block_minecart" = 0x2a,
    "set_creative_slot" = 0x2b,
    "update_jigsaw_block" = 0x2c,
    "update_structure_block" = 0x2d,
    "update_sign" = 0x2e,
    "arm_animation" = 0x2f,
    "spectate" = 0x30,
    "block_place" = 0x31,
    "use_item" = 0x32,
}

