// Because enums cannot be nested within other types, they must all be hoisted

declare const enum SlotComponentType {
    "custom_data" = 0,
    "max_stack_size" = 1,
    "max_damage" = 2,
    "damage" = 3,
    "unbreakable" = 4,
    "custom_name" = 5,
    "item_name" = 6,
    "lore" = 7,
    "rarity" = 8,
    "enchantments" = 9,
    "can_place_on" = 10,
    "can_break" = 11,
    "attribute_modifiers" = 12,
    "custom_model_data" = 13,
    "hide_additional_tooltip" = 14,
    "hide_tooltip" = 15,
    "repair_cost" = 16,
    "creative_slot_lock" = 17,
    "enchantment_glint_override" = 18,
    "intangible_projectile" = 19,
    "food" = 20,
    "fire_resistant" = 21,
    "tool" = 22,
    "stored_enchantments" = 23,
    "dyed_color" = 24,
    "map_color" = 25,
    "map_id" = 26,
    "map_decorations" = 27,
    "map_post_processing" = 28,
    "charged_projectiles" = 29,
    "bundle_contents" = 30,
    "potion_contents" = 31,
    "suspicious_stew_effects" = 32,
    "writable_book_content" = 33,
    "written_book_content" = 34,
    "trim" = 35,
    "debug_stick_state" = 36,
    "entity_data" = 37,
    "bucket_entity_data" = 38,
    "block_entity_data" = 39,
    "instrument" = 40,
    "ominous_bottle_amplifier" = 41,
    "jukebox_playable" = 42,
    "recipes" = 43,
    "lodestone_tracker" = 44,
    "firework_explosion" = 45,
    "fireworks" = 46,
    "profile" = 47,
    "note_block_sound" = 48,
    "banner_patterns" = 49,
    "base_color" = 50,
    "pot_decorations" = 51,
    "container" = 52,
    "block_state" = 53,
    "bees" = 54,
    "lock" = 55,
    "container_loot" = 56,
}

declare const enum attribute_modifiers_attributes_operation {
    "add" = 0,
    "multiply_base" = 1,
    "multiply_total" = 2,
}

declare const enum attribute_modifiers_attributes_slot {
    "any" = 0,
    "main_hand" = 1,
    "off_hand" = 2,
    "hand" = 3,
    "feet" = 4,
    "legs" = 5,
    "chest" = 6,
    "head" = 7,
    "armor" = 8,
    "body" = 9,
}

declare const enum ItemFireworkExplosion_shape {
    "small_ball" = 0,
    "large_ball" = 1,
    "star" = 2,
    "creeper" = 3,
    "burst" = 4,
}

declare const enum Particle_type {
    "angry_villager" = 0,
    "block" = 1,
    "block_marker" = 2,
    "bubble" = 3,
    "cloud" = 4,
    "crit" = 5,
    "damage_indicator" = 6,
    "dragon_breath" = 7,
    "dripping_lava" = 8,
    "falling_lava" = 9,
    "landing_lava" = 10,
    "dripping_water" = 11,
    "falling_water" = 12,
    "dust" = 13,
    "dust_color_transition" = 14,
    "effect" = 15,
    "elder_guardian" = 16,
    "enchanted_hit" = 17,
    "enchant" = 18,
    "end_rod" = 19,
    "entity_effect" = 20,
    "explosion_emitter" = 21,
    "explosion" = 22,
    "gust" = 23,
    "small_gust" = 24,
    "gust_emitter_large" = 25,
    "gust_emitter_small" = 26,
    "sonic_boom" = 27,
    "falling_dust" = 28,
    "firework" = 29,
    "fishing" = 30,
    "flame" = 31,
    "infested" = 32,
    "cherry_leaves" = 33,
    "sculk_soul" = 34,
    "sculk_charge" = 35,
    "sculk_charge_pop" = 36,
    "soul_fire_flame" = 37,
    "soul" = 38,
    "flash" = 39,
    "happy_villager" = 40,
    "composter" = 41,
    "heart" = 42,
    "instant_effect" = 43,
    "item" = 44,
    "vibration" = 45,
    "item_slime" = 46,
    "item_cobweb" = 47,
    "item_snowball" = 48,
    "large_smoke" = 49,
    "lava" = 50,
    "mycelium" = 51,
    "note" = 52,
    "poof" = 53,
    "portal" = 54,
    "rain" = 55,
    "smoke" = 56,
    "white_smoke" = 57,
    "sneeze" = 58,
    "spit" = 59,
    "squid_ink" = 60,
    "sweep_attack" = 61,
    "totem_of_undying" = 62,
    "underwater" = 63,
    "splash" = 64,
    "witch" = 65,
    "bubble_pop" = 66,
    "current_down" = 67,
    "bubble_column_up" = 68,
    "nautilus" = 69,
    "dolphin" = 70,
    "campfire_cosy_smoke" = 71,
    "campfire_signal_smoke" = 72,
    "dripping_honey" = 73,
    "falling_honey" = 74,
    "landing_honey" = 75,
    "falling_nectar" = 76,
    "falling_spore_blossom" = 77,
    "ash" = 78,
    "crimson_spore" = 79,
    "warped_spore" = 80,
    "spore_blossom_air" = 81,
    "dripping_obsidian_tear" = 82,
    "falling_obsidian_tear" = 83,
    "landing_obsidian_tear" = 84,
    "reverse_portal" = 85,
    "white_ash" = 86,
    "small_flame" = 87,
    "snowflake" = 88,
    "dripping_dripstone_lava" = 89,
    "falling_dripstone_lava" = 90,
    "dripping_dripstone_water" = 91,
    "falling_dripstone_water" = 92,
    "glow_squid_ink" = 93,
    "glow" = 94,
    "wax_on" = 95,
    "wax_off" = 96,
    "electric_spark" = 97,
    "scrape" = 98,
    "shriek" = 99,
    "egg_crack" = 100,
    "dust_plume" = 101,
    "trial_spawner_detected_player" = 102,
    "trial_spawner_detected_player_ominous" = 103,
    "vault_connection" = 104,
    "dust_pillar" = 105,
    "ominous_spawning" = 106,
    "raid_omen" = 107,
    "trial_omen" = 108,
}

declare const enum vibration_positionType {
    "block" = 0,
    "entity" = 1,
}

declare const enum soundSource {
    "master" = 0,
    "music" = 1,
    "record" = 2,
    "weather" = 3,
    "block" = 4,
    "hostile" = 5,
    "neutral" = 6,
    "player" = 7,
    "ambient" = 8,
    "voice" = 9,
}

declare const enum entityMetadataEntry_type {
    "byte" = 0,
    "int" = 1,
    "long" = 2,
    "float" = 3,
    "string" = 4,
    "component" = 5,
    "optional_component" = 6,
    "item_stack" = 7,
    "boolean" = 8,
    "rotations" = 9,
    "block_pos" = 10,
    "optional_block_pos" = 11,
    "direction" = 12,
    "optional_uuid" = 13,
    "block_state" = 14,
    "optional_block_state" = 15,
    "compound_tag" = 16,
    "particle" = 17,
    "particles" = 18,
    "villager_data" = 19,
    "optional_unsigned_int" = 20,
    "pose" = 21,
    "cat_variant" = 22,
    "wolf_variant" = 23,
    "frog_variant" = 24,
    "optional_global_pos" = 25,
    "painting_variant" = 26,
    "sniffer_state" = 27,
    "armadillo_state" = 28,
    "vector3" = 29,
    "quaternion" = 30,
}

declare const enum a2_parser {
    "brigadier:bool" = 0,
    "brigadier:float" = 1,
    "brigadier:double" = 2,
    "brigadier:integer" = 3,
    "brigadier:long" = 4,
    "brigadier:string" = 5,
    "minecraft:entity" = 6,
    "minecraft:game_profile" = 7,
    "minecraft:block_pos" = 8,
    "minecraft:column_pos" = 9,
    "minecraft:vec3" = 10,
    "minecraft:vec2" = 11,
    "minecraft:block_state" = 12,
    "minecraft:block_predicate" = 13,
    "minecraft:item_stack" = 14,
    "minecraft:item_predicate" = 15,
    "minecraft:color" = 16,
    "minecraft:component" = 17,
    "minecraft:style" = 18,
    "minecraft:message" = 19,
    "minecraft:nbt" = 20,
    "minecraft:nbt_tag" = 21,
    "minecraft:nbt_path" = 22,
    "minecraft:objective" = 23,
    "minecraft:objective_criteria" = 24,
    "minecraft:operation" = 25,
    "minecraft:particle" = 26,
    "minecraft:angle" = 27,
    "minecraft:rotation" = 28,
    "minecraft:scoreboard_slot" = 29,
    "minecraft:score_holder" = 30,
    "minecraft:swizzle" = 31,
    "minecraft:team" = 32,
    "minecraft:item_slot" = 33,
    "minecraft:item_slots" = 34,
    "minecraft:resource_location" = 35,
    "minecraft:function" = 36,
    "minecraft:entity_anchor" = 37,
    "minecraft:int_range" = 38,
    "minecraft:float_range" = 39,
    "minecraft:dimension" = 40,
    "minecraft:gamemode" = 41,
    "minecraft:time" = 42,
    "minecraft:resource_or_tag" = 43,
    "minecraft:resource_or_tag_key" = 44,
    "minecraft:resource" = 45,
    "minecraft:resource_key" = 46,
    "minecraft:template_mirror" = 47,
    "minecraft:template_rotation" = 48,
    "minecraft:heightmap" = 49,
    "minecraft:loot_table" = 50,
    "minecraft:loot_predicate" = 51,
    "minecraft:loot_modifier" = 52,
    "minecraft:uuid" = 53,
}

declare const enum ServerLinkType {
    "bug_report" = 0,
    "community_guidelines" = 1,
    "support" = 2,
    "status" = 3,
    "feedback" = 4,
    "community" = 5,
    "website" = 6,
    "forums" = 7,
    "news" = 8,
    "announcements" = 9,
}

declare const enum packet_name {
}

declare const enum packet_name_2 {
    "set_protocol" = 0x00,
    "legacy_server_list_ping" = 0xfe,
}

declare const enum packet_name_3 {
    "server_info" = 0x00,
    "ping" = 0x01,
}

declare const enum packet_name_4 {
    "ping_start" = 0x00,
    "ping" = 0x01,
}

declare const enum packet_name_5 {
    "disconnect" = 0x00,
    "encryption_begin" = 0x01,
    "success" = 0x02,
    "compress" = 0x03,
    "login_plugin_request" = 0x04,
    "cookie_request" = 0x05,
}

declare const enum packet_name_6 {
    "login_start" = 0x00,
    "encryption_begin" = 0x01,
    "login_plugin_response" = 0x02,
    "login_acknowledged" = 0x03,
    "cookie_response" = 0x04,
}

declare const enum packet_name_7 {
    "cookie_request" = 0x00,
    "custom_payload" = 0x01,
    "disconnect" = 0x02,
    "finish_configuration" = 0x03,
    "keep_alive" = 0x04,
    "ping" = 0x05,
    "reset_chat" = 0x06,
    "registry_data" = 0x07,
    "remove_resource_pack" = 0x08,
    "add_resource_pack" = 0x09,
    "store_cookie" = 0x0a,
    "transfer" = 0x0b,
    "feature_flags" = 0x0c,
    "tags" = 0x0d,
    "select_known_packs" = 0x0e,
    "custom_report_details" = 0x0f,
    "server_links" = 0x10,
}

declare const enum packet_name_8 {
    "settings" = 0x00,
    "cookie_response" = 0x01,
    "custom_payload" = 0x02,
    "finish_configuration" = 0x03,
    "keep_alive" = 0x04,
    "pong" = 0x05,
    "resource_pack_receive" = 0x06,
    "select_known_packs" = 0x07,
    "custom_report_details" = 0x08,
    "server_links" = 0x09,
}

declare const enum SpawnInfo_gamemode {
    "survival" = 0,
    "creative" = 1,
    "adventure" = 2,
    "spectator" = 3,
}

declare const enum ChatTypeParameterType {
    "content" = 0,
    "sender" = 1,
    "target" = 2,
}

declare const enum packet_player_info_action_bitflags {
    add_player = 1 << 0,
    initialize_chat = 1 << 1,
    update_game_mode = 1 << 2,
    update_listed = 1 << 3,
    update_latency = 1 << 4,
    update_display_name = 1 << 5,
}

declare const enum PositionUpdateRelatives_bitflags {
    x = 1 << 0,
    y = 1 << 1,
    z = 1 << 2,
    yaw = 1 << 3,
    pitch = 1 << 4,
}

declare const enum packet_entity_update_attributes_properties_key {
    "generic.armor" = 0,
    "generic.armor_toughness" = 1,
    "generic.attack_damage" = 2,
    "generic.attack_knockback" = 3,
    "generic.attack_speed" = 4,
    "player.block_break_speed" = 5,
    "player.block_interaction_range" = 6,
    "player.entity_interaction_range" = 7,
    "generic.fall_damage_multiplier" = 8,
    "generic.flying_speed" = 9,
    "generic.follow_range" = 10,
    "generic.gravity" = 11,
    "generic.jump_strength" = 12,
    "generic.knockback_resistance" = 13,
    "generic.luck" = 14,
    "generic.max_absorption" = 15,
    "generic.max_health" = 16,
    "generic.movement_speed" = 17,
    "generic.safe_fall_distance" = 18,
    "generic.scale" = 19,
    "zombie.spawn_reinforcements" = 20,
    "generic.step_height" = 21,
}

declare const enum packet_declare_recipes_recipes_type {
    "minecraft:crafting_shaped" = 0,
    "minecraft:crafting_shapeless" = 1,
    "minecraft:crafting_special_armordye" = 2,
    "minecraft:crafting_special_bookcloning" = 3,
    "minecraft:crafting_special_mapcloning" = 4,
    "minecraft:crafting_special_mapextending" = 5,
    "minecraft:crafting_special_firework_rocket" = 6,
    "minecraft:crafting_special_firework_star" = 7,
    "minecraft:crafting_special_firework_star_fade" = 8,
    "minecraft:crafting_special_tippedarrow" = 9,
    "minecraft:crafting_special_bannerduplicate" = 10,
    "minecraft:crafting_special_shielddecoration" = 11,
    "minecraft:crafting_special_shulkerboxcoloring" = 12,
    "minecraft:crafting_special_suspiciousstew" = 13,
    "minecraft:crafting_special_repairitem" = 14,
    "minecraft:smelting" = 15,
    "minecraft:blasting" = 16,
    "minecraft:smoking" = 17,
    "minecraft:campfire_cooking" = 18,
    "minecraft:stonecutting" = 19,
    "minecraft:smithing_transform" = 20,
    "minecraft:smithing_trim" = 21,
    "minecraft:crafting_decorated_pot" = 22,
}

declare const enum packet_name_9 {
    "bundle_delimiter" = 0x00,
    "spawn_entity" = 0x01,
    "spawn_entity_experience_orb" = 0x02,
    "animation" = 0x03,
    "statistics" = 0x04,
    "acknowledge_player_digging" = 0x05,
    "block_break_animation" = 0x06,
    "tile_entity_data" = 0x07,
    "block_action" = 0x08,
    "block_change" = 0x09,
    "boss_bar" = 0x0a,
    "difficulty" = 0x0b,
    "chunk_batch_finished" = 0x0c,
    "chunk_batch_start" = 0x0d,
    "chunk_biomes" = 0x0e,
    "clear_titles" = 0x0f,
    "tab_complete" = 0x10,
    "declare_commands" = 0x11,
    "close_window" = 0x12,
    "window_items" = 0x13,
    "craft_progress_bar" = 0x14,
    "set_slot" = 0x15,
    "cookie_request" = 0x16,
    "set_cooldown" = 0x17,
    "chat_suggestions" = 0x18,
    "custom_payload" = 0x19,
    "damage_event" = 0x1a,
    "debug_sample" = 0x1b,
    "hide_message" = 0x1c,
    "kick_disconnect" = 0x1d,
    "profileless_chat" = 0x1e,
    "entity_status" = 0x1f,
    "explosion" = 0x20,
    "unload_chunk" = 0x21,
    "game_state_change" = 0x22,
    "open_horse_window" = 0x23,
    "hurt_animation" = 0x24,
    "initialize_world_border" = 0x25,
    "keep_alive" = 0x26,
    "map_chunk" = 0x27,
    "world_event" = 0x28,
    "world_particles" = 0x29,
    "update_light" = 0x2a,
    "login" = 0x2b,
    "map" = 0x2c,
    "trade_list" = 0x2d,
    "rel_entity_move" = 0x2e,
    "entity_move_look" = 0x2f,
    "entity_look" = 0x30,
    "vehicle_move" = 0x31,
    "open_book" = 0x32,
    "open_window" = 0x33,
    "open_sign_entity" = 0x34,
    "ping" = 0x35,
    "ping_response" = 0x36,
    "craft_recipe_response" = 0x37,
    "abilities" = 0x38,
    "player_chat" = 0x39,
    "end_combat_event" = 0x3a,
    "enter_combat_event" = 0x3b,
    "death_combat_event" = 0x3c,
    "player_remove" = 0x3d,
    "player_info" = 0x3e,
    "face_player" = 0x3f,
    "position" = 0x40,
    "unlock_recipes" = 0x41,
    "entity_destroy" = 0x42,
    "remove_entity_effect" = 0x43,
    "reset_score" = 0x44,
    "remove_resource_pack" = 0x45,
    "add_resource_pack" = 0x46,
    "respawn" = 0x47,
    "entity_head_rotation" = 0x48,
    "multi_block_change" = 0x49,
    "select_advancement_tab" = 0x4a,
    "server_data" = 0x4b,
    "action_bar" = 0x4c,
    "world_border_center" = 0x4d,
    "world_border_lerp_size" = 0x4e,
    "world_border_size" = 0x4f,
    "world_border_warning_delay" = 0x50,
    "world_border_warning_reach" = 0x51,
    "camera" = 0x52,
    "held_item_slot" = 0x53,
    "update_view_position" = 0x54,
    "update_view_distance" = 0x55,
    "spawn_position" = 0x56,
    "scoreboard_display_objective" = 0x57,
    "entity_metadata" = 0x58,
    "attach_entity" = 0x59,
    "entity_velocity" = 0x5a,
    "entity_equipment" = 0x5b,
    "experience" = 0x5c,
    "update_health" = 0x5d,
    "scoreboard_objective" = 0x5e,
    "set_passengers" = 0x5f,
    "teams" = 0x60,
    "scoreboard_score" = 0x61,
    "simulation_distance" = 0x62,
    "set_title_subtitle" = 0x63,
    "update_time" = 0x64,
    "set_title_text" = 0x65,
    "set_title_time" = 0x66,
    "entity_sound_effect" = 0x67,
    "sound_effect" = 0x68,
    "start_configuration" = 0x69,
    "stop_sound" = 0x6a,
    "store_cookie" = 0x6b,
    "system_chat" = 0x6c,
    "playerlist_header" = 0x6d,
    "nbt_query_response" = 0x6e,
    "collect" = 0x6f,
    "entity_teleport" = 0x70,
    "set_ticking_state" = 0x71,
    "step_tick" = 0x72,
    "transfer" = 0x73,
    "advancements" = 0x74,
    "entity_update_attributes" = 0x75,
    "entity_effect" = 0x76,
    "declare_recipes" = 0x77,
    "tags" = 0x78,
    "set_projectile_power" = 0x79,
    "custom_report_details" = 0x7a,
    "server_links" = 0x7b,
}

declare const enum packet_name_10 {
    "teleport_confirm" = 0x00,
    "query_block_nbt" = 0x01,
    "set_difficulty" = 0x02,
    "message_acknowledgement" = 0x03,
    "chat_command" = 0x04,
    "chat_command_signed" = 0x05,
    "chat_message" = 0x06,
    "chat_session_update" = 0x07,
    "chunk_batch_received" = 0x08,
    "client_command" = 0x09,
    "settings" = 0x0a,
    "tab_complete" = 0x0b,
    "configuration_acknowledged" = 0x0c,
    "enchant_item" = 0x0d,
    "window_click" = 0x0e,
    "close_window" = 0x0f,
    "set_slot_state" = 0x10,
    "cookie_response" = 0x11,
    "custom_payload" = 0x12,
    "debug_sample_subscription" = 0x13,
    "edit_book" = 0x14,
    "query_entity_nbt" = 0x15,
    "use_entity" = 0x16,
    "generate_structure" = 0x17,
    "keep_alive" = 0x18,
    "lock_difficulty" = 0x19,
    "position" = 0x1a,
    "position_look" = 0x1b,
    "look" = 0x1c,
    "flying" = 0x1d,
    "vehicle_move" = 0x1e,
    "steer_boat" = 0x1f,
    "pick_item" = 0x20,
    "ping_request" = 0x21,
    "craft_recipe_request" = 0x22,
    "abilities" = 0x23,
    "block_dig" = 0x24,
    "entity_action" = 0x25,
    "steer_vehicle" = 0x26,
    "pong" = 0x27,
    "recipe_book" = 0x28,
    "displayed_recipe" = 0x29,
    "name_item" = 0x2a,
    "resource_pack_receive" = 0x2b,
    "advancement_tab" = 0x2c,
    "select_trade" = 0x2d,
    "set_beacon_effect" = 0x2e,
    "held_item_slot" = 0x2f,
    "update_command_block" = 0x30,
    "update_command_block_minecart" = 0x31,
    "set_creative_slot" = 0x32,
    "update_jigsaw_block" = 0x33,
    "update_structure_block" = 0x34,
    "update_sign" = 0x35,
    "arm_animation" = 0x36,
    "spectate" = 0x37,
    "block_place" = 0x38,
    "use_item" = 0x39,
}

