// Because enums cannot be nested within other types, they must all be hoisted

declare const enum SlotComponentType {
    "custom_data" = 0,
    "max_stack_size" = 1,
    "max_damage" = 2,
    "damage" = 3,
    "unbreakable" = 4,
    "custom_name" = 5,
    "item_name" = 6,
    "item_model" = 7,
    "lore" = 8,
    "rarity" = 9,
    "enchantments" = 10,
    "can_place_on" = 11,
    "can_break" = 12,
    "attribute_modifiers" = 13,
    "custom_model_data" = 14,
    "tooltip_display" = 15,
    "repair_cost" = 16,
    "creative_slot_lock" = 17,
    "enchantment_glint_override" = 18,
    "intangible_projectile" = 19,
    "food" = 20,
    "consumable" = 21,
    "use_remainder" = 22,
    "use_cooldown" = 23,
    "damage_resistant" = 24,
    "tool" = 25,
    "weapon" = 26,
    "enchantable" = 27,
    "equippable" = 28,
    "repairable" = 29,
    "glider" = 30,
    "tooltip_style" = 31,
    "death_protection" = 32,
    "blocks_attacks" = 33,
    "stored_enchantments" = 34,
    "dyed_color" = 35,
    "map_color" = 36,
    "map_id" = 37,
    "map_decorations" = 38,
    "map_post_processing" = 39,
    "charged_projectiles" = 40,
    "bundle_contents" = 41,
    "potion_contents" = 42,
    "potion_duration_scale" = 43,
    "suspicious_stew_effects" = 44,
    "writable_book_content" = 45,
    "written_book_content" = 46,
    "trim" = 47,
    "debug_stick_state" = 48,
    "entity_data" = 49,
    "bucket_entity_data" = 50,
    "block_entity_data" = 51,
    "instrument" = 52,
    "provides_trim_material" = 53,
    "ominous_bottle_amplifier" = 54,
    "jukebox_playable" = 55,
    "provides_banner_patterns" = 56,
    "recipes" = 57,
    "lodestone_tracker" = 58,
    "firework_explosion" = 59,
    "fireworks" = 60,
    "profile" = 61,
    "note_block_sound" = 62,
    "banner_patterns" = 63,
    "base_color" = 64,
    "pot_decorations" = 65,
    "container" = 66,
    "block_state" = 67,
    "bees" = 68,
    "lock" = 69,
    "container_loot" = 70,
    "break_sound" = 71,
    "villager_variant" = 72,
    "wolf_variant" = 73,
    "wolf_sound_variant" = 74,
    "wolf_collar" = 75,
    "fox_variant" = 76,
    "salmon_size" = 77,
    "parrot_variant" = 78,
    "tropical_fish_pattern" = 79,
    "tropical_fish_base_color" = 80,
    "tropical_fish_pattern_color" = 81,
    "mooshroom_variant" = 82,
    "rabbit_variant" = 83,
    "pig_variant" = 84,
    "cow_variant" = 85,
    "chicken_variant" = 86,
    "frog_variant" = 87,
    "horse_variant" = 88,
    "painting_variant" = 89,
    "llama_variant" = 90,
    "axolotl_variant" = 91,
    "cat_variant" = 92,
    "cat_collar" = 93,
    "sheep_color" = 94,
    "shulker_color" = 95,
}

declare const enum consumable_animation {
    "none" = 0,
    "eat" = 1,
    "drink" = 2,
    "block" = 3,
    "bow" = 4,
    "spear" = 5,
    "crossbow" = 6,
    "spyglass" = 7,
    "toot_horn" = 8,
    "brush" = 9,
    "bundle" = 10,
}

declare const enum equippable_slot {
    "main_hand" = 0,
    "off_hand" = 1,
    "feet" = 2,
    "legs" = 3,
    "chest" = 4,
    "head" = 5,
    "body" = 6,
    "saddle" = 7,
}

declare const enum ItemFireworkExplosion_shape {
    "small_ball" = 0,
    "large_ball" = 1,
    "star" = 2,
    "creeper" = 3,
    "burst" = 4,
}

declare const enum ItemConsumeEffect_type {
    "apply_effects" = 0,
    "remove_effects" = 1,
    "clear_all_effects" = 2,
    "teleport_randomly" = 3,
    "play_sound" = 4,
}

declare const enum Particle_type {
    "angry_villager" = 0,
    "block" = 1,
    "block_marker" = 2,
    "bubble" = 3,
    "cloud" = 4,
    "crit" = 5,
    "damage_indicator" = 6,
    "dragon_breath" = 7,
    "dripping_lava" = 8,
    "falling_lava" = 9,
    "landing_lava" = 10,
    "dripping_water" = 11,
    "falling_water" = 12,
    "dust" = 13,
    "dust_color_transition" = 14,
    "effect" = 15,
    "elder_guardian" = 16,
    "enchanted_hit" = 17,
    "enchant" = 18,
    "end_rod" = 19,
    "entity_effect" = 20,
    "explosion_emitter" = 21,
    "explosion" = 22,
    "gust" = 23,
    "small_gust" = 24,
    "gust_emitter_large" = 25,
    "gust_emitter_small" = 26,
    "sonic_boom" = 27,
    "falling_dust" = 28,
    "firework" = 29,
    "fishing" = 30,
    "flame" = 31,
    "infested" = 32,
    "cherry_leaves" = 33,
    "pale_oak_leaves" = 34,
    "tinted_leaves" = 35,
    "sculk_soul" = 36,
    "sculk_charge" = 37,
    "sculk_charge_pop" = 38,
    "soul_fire_flame" = 39,
    "soul" = 40,
    "flash" = 41,
    "happy_villager" = 42,
    "composter" = 43,
    "heart" = 44,
    "instant_effect" = 45,
    "item" = 46,
    "vibration" = 47,
    "trail" = 48,
    "item_slime" = 49,
    "item_cobweb" = 50,
    "item_snowball" = 51,
    "large_smoke" = 52,
    "lava" = 53,
    "mycelium" = 54,
    "note" = 55,
    "poof" = 56,
    "portal" = 57,
    "rain" = 58,
    "smoke" = 59,
    "white_smoke" = 60,
    "sneeze" = 61,
    "spit" = 62,
    "squid_ink" = 63,
    "sweep_attack" = 64,
    "totem_of_undying" = 65,
    "underwater" = 66,
    "splash" = 67,
    "witch" = 68,
    "bubble_pop" = 69,
    "current_down" = 70,
    "bubble_column_up" = 71,
    "nautilus" = 72,
    "dolphin" = 73,
    "campfire_cosy_smoke" = 74,
    "campfire_signal_smoke" = 75,
    "dripping_honey" = 76,
    "falling_honey" = 77,
    "landing_honey" = 78,
    "falling_nectar" = 79,
    "falling_spore_blossom" = 80,
    "ash" = 81,
    "crimson_spore" = 82,
    "warped_spore" = 83,
    "spore_blossom_air" = 84,
    "dripping_obsidian_tear" = 85,
    "falling_obsidian_tear" = 86,
    "landing_obsidian_tear" = 87,
    "reverse_portal" = 88,
    "white_ash" = 89,
    "small_flame" = 90,
    "snowflake" = 91,
    "dripping_dripstone_lava" = 92,
    "falling_dripstone_lava" = 93,
    "dripping_dripstone_water" = 94,
    "falling_dripstone_water" = 95,
    "glow_squid_ink" = 96,
    "glow" = 97,
    "wax_on" = 98,
    "wax_off" = 99,
    "electric_spark" = 100,
    "scrape" = 101,
    "shriek" = 102,
    "egg_crack" = 103,
    "dust_plume" = 104,
    "trial_spawner_detected_player" = 105,
    "trial_spawner_detected_player_ominous" = 106,
    "vault_connection" = 107,
    "dust_pillar" = 108,
    "ominous_spawning" = 109,
    "raid_omen" = 110,
    "trial_omen" = 111,
    "block_crumble" = 112,
    "firefly" = 113,
}

declare const enum vibration_positionType {
    "block" = 0,
    "entity" = 1,
}

declare const enum soundSource {
    "master" = 0,
    "music" = 1,
    "record" = 2,
    "weather" = 3,
    "block" = 4,
    "hostile" = 5,
    "neutral" = 6,
    "player" = 7,
    "ambient" = 8,
    "voice" = 9,
    "ui" = 10,
}

declare const enum entityMetadataEntry_type {
    "byte" = 0,
    "int" = 1,
    "long" = 2,
    "float" = 3,
    "string" = 4,
    "component" = 5,
    "optional_component" = 6,
    "item_stack" = 7,
    "boolean" = 8,
    "rotations" = 9,
    "block_pos" = 10,
    "optional_block_pos" = 11,
    "direction" = 12,
    "optional_uuid" = 13,
    "block_state" = 14,
    "optional_block_state" = 15,
    "compound_tag" = 16,
    "particle" = 17,
    "particles" = 18,
    "villager_data" = 19,
    "optional_unsigned_int" = 20,
    "pose" = 21,
    "cat_variant" = 22,
    "cow_variant" = 23,
    "wolf_variant" = 24,
    "wolf_sound_variant" = 25,
    "frog_variant" = 26,
    "pig_variant" = 27,
    "chicken_variant" = 28,
    "optional_global_pos" = 29,
    "painting_variant" = 30,
    "sniffer_state" = 31,
    "armadillo_state" = 32,
    "vector3" = 33,
    "quaternion" = 34,
}

declare const enum a2_parser {
    "brigadier:bool" = 0,
    "brigadier:float" = 1,
    "brigadier:double" = 2,
    "brigadier:integer" = 3,
    "brigadier:long" = 4,
    "brigadier:string" = 5,
    "minecraft:entity" = 6,
    "minecraft:game_profile" = 7,
    "minecraft:block_pos" = 8,
    "minecraft:column_pos" = 9,
    "minecraft:vec3" = 10,
    "minecraft:vec2" = 11,
    "minecraft:block_state" = 12,
    "minecraft:block_predicate" = 13,
    "minecraft:item_stack" = 14,
    "minecraft:item_predicate" = 15,
    "minecraft:color" = 16,
    "minecraft:hex_color" = 17,
    "minecraft:component" = 18,
    "minecraft:style" = 19,
    "minecraft:message" = 20,
    "minecraft:nbt" = 21,
    "minecraft:nbt_tag" = 22,
    "minecraft:nbt_path" = 23,
    "minecraft:objective" = 24,
    "minecraft:objective_criteria" = 25,
    "minecraft:operation" = 26,
    "minecraft:particle" = 27,
    "minecraft:angle" = 28,
    "minecraft:rotation" = 29,
    "minecraft:scoreboard_slot" = 30,
    "minecraft:score_holder" = 31,
    "minecraft:swizzle" = 32,
    "minecraft:team" = 33,
    "minecraft:item_slot" = 34,
    "minecraft:item_slots" = 35,
    "minecraft:resource_location" = 36,
    "minecraft:function" = 37,
    "minecraft:entity_anchor" = 38,
    "minecraft:int_range" = 39,
    "minecraft:float_range" = 40,
    "minecraft:dimension" = 41,
    "minecraft:gamemode" = 42,
    "minecraft:time" = 43,
    "minecraft:resource_or_tag" = 44,
    "minecraft:resource_or_tag_key" = 45,
    "minecraft:resource" = 46,
    "minecraft:resource_key" = 47,
    "minecraft:resource_selector" = 48,
    "minecraft:template_mirror" = 49,
    "minecraft:template_rotation" = 50,
    "minecraft:heightmap" = 51,
    "minecraft:loot_table" = 52,
    "minecraft:loot_predicate" = 53,
    "minecraft:loot_modifier" = 54,
    "minecraft:dialog" = 55,
    "minecraft:uuid" = 56,
}

declare const enum packet_common_settings_particleStatus {
    "all" = 0,
    "decreased" = 1,
    "minimal" = 2,
}

declare const enum ServerLinkType {
    "bug_report" = 0,
    "community_guidelines" = 1,
    "support" = 2,
    "status" = 3,
    "feedback" = 4,
    "community" = 5,
    "website" = 6,
    "forums" = 7,
    "news" = 8,
    "announcements" = 9,
}

declare const enum packet_name {
}

declare const enum packet_name_2 {
    "set_protocol" = 0x00,
    "legacy_server_list_ping" = 0xfe,
}

declare const enum packet_name_3 {
    "server_info" = 0x00,
    "ping" = 0x01,
}

declare const enum packet_name_4 {
    "ping_start" = 0x00,
    "ping" = 0x01,
}

declare const enum packet_name_5 {
    "disconnect" = 0x00,
    "encryption_begin" = 0x01,
    "success" = 0x02,
    "compress" = 0x03,
    "login_plugin_request" = 0x04,
    "cookie_request" = 0x05,
}

declare const enum packet_name_6 {
    "login_start" = 0x00,
    "encryption_begin" = 0x01,
    "login_plugin_response" = 0x02,
    "login_acknowledged" = 0x03,
    "cookie_response" = 0x04,
}

declare const enum packet_name_7 {
    "cookie_request" = 0x00,
    "custom_payload" = 0x01,
    "disconnect" = 0x02,
    "finish_configuration" = 0x03,
    "keep_alive" = 0x04,
    "ping" = 0x05,
    "reset_chat" = 0x06,
    "registry_data" = 0x07,
    "remove_resource_pack" = 0x08,
    "add_resource_pack" = 0x09,
    "store_cookie" = 0x0a,
    "transfer" = 0x0b,
    "feature_flags" = 0x0c,
    "tags" = 0x0d,
    "select_known_packs" = 0x0e,
    "custom_report_details" = 0x0f,
    "server_links" = 0x10,
    "clear_dialog" = 0x11,
    "show_dialog" = 0x12,
}

declare const enum packet_name_8 {
    "settings" = 0x00,
    "cookie_response" = 0x01,
    "custom_payload" = 0x02,
    "finish_configuration" = 0x03,
    "keep_alive" = 0x04,
    "pong" = 0x05,
    "resource_pack_receive" = 0x06,
    "select_known_packs" = 0x07,
    "custom_click_action" = 0x08,
}

declare const enum SlotDisplay_type {
    "empty" = 0,
    "any_fuel" = 1,
    "item" = 2,
    "item_stack" = 3,
    "tag" = 4,
    "smithing_trim" = 5,
    "with_remainder" = 6,
    "composite" = 7,
}

declare const enum RecipeDisplay_type {
    "crafting_shapeless" = 0,
    "crafting_shaped" = 1,
    "furnace" = 2,
    "stonecutter" = 3,
    "smithing" = 4,
}

declare const enum SpawnInfo_gamemode {
    "survival" = 0,
    "creative" = 1,
    "adventure" = 2,
    "spectator" = 3,
}

declare const enum packet_difficulty_difficulty {
    "peaceful" = 0,
    "easy" = 1,
    "normal" = 2,
    "hard" = 3,
}

declare const enum ChatTypeParameterType {
    "content" = 0,
    "sender" = 1,
    "target" = 2,
}

declare const enum packet_game_state_change_reason {
    "no_respawn_block_available" = 0,
    "start_raining" = 1,
    "stop_raining" = 2,
    "change_game_mode" = 3,
    "win_game" = 4,
    "demo_event" = 5,
    "play_arrow_hit_sound" = 6,
    "rain_level_change" = 7,
    "thunder_level_change" = 8,
    "puffer_fish_sting" = 9,
    "guardian_elder_effect" = 10,
    "immediate_respawn" = 11,
    "limited_crafting" = 12,
    "level_chunks_load_start" = 13,
}

declare const enum packet_map_chunk_heightmaps_type {
    "world_surface_wg" = 0,
    "world_surface" = 1,
    "ocean_floor_wg" = 2,
    "ocean_floor" = 3,
    "motion_blocking" = 4,
    "motion_blocking_no_leaves" = 5,
}

declare const enum packet_player_info_action_bitflags {
    add_player = 1 << 0,
    initialize_chat = 1 << 1,
    update_game_mode = 1 << 2,
    update_listed = 1 << 3,
    update_latency = 1 << 4,
    update_display_name = 1 << 5,
    update_hat = 1 << 6,
    update_list_order = 1 << 7,
}

declare const enum PositionUpdateRelatives_bitflags {
    x = 1 << 0,
    y = 1 << 1,
    z = 1 << 2,
    yaw = 1 << 3,
    pitch = 1 << 4,
    dx = 1 << 5,
    dy = 1 << 6,
    dz = 1 << 7,
    yawDelta = 1 << 8,
}

declare const enum packet_recipe_book_add_entries_recipe_category {
    "crafting_building_blocks" = 0,
    "crafting_redstone" = 1,
    "crafting_equipment" = 2,
    "crafting_misc" = 3,
    "furnace_food" = 4,
    "furnace_blocks" = 5,
    "furnace_misc" = 6,
    "blast_furnace_blocks" = 7,
    "blast_furnace_misc" = 8,
    "smoker_food" = 9,
    "stonecutter" = 10,
    "smithing" = 11,
    "campfire" = 12,
}

declare const enum packet_recipe_book_add_entries_flags_bitflags {
    notification = 1 << 0,
    highlight = 1 << 1,
}

declare const enum packet_teams_mode {
    "add" = 0,
    "remove" = 1,
    "change" = 2,
    "join" = 3,
    "leave" = 4,
}

declare const enum packet_entity_update_attributes_properties_key {
    "generic.armor" = 0,
    "generic.armor_toughness" = 1,
    "generic.attack_damage" = 2,
    "generic.attack_knockback" = 3,
    "generic.attack_speed" = 4,
    "player.block_break_speed" = 5,
    "player.block_interaction_range" = 6,
    "burning_time" = 7,
    "camera_distance" = 8,
    "explosion_knockback_resistance" = 9,
    "player.entity_interaction_range" = 10,
    "generic.fall_damage_multiplier" = 11,
    "generic.flying_speed" = 12,
    "generic.follow_range" = 13,
    "generic.gravity" = 14,
    "generic.jump_strength" = 15,
    "generic.knockback_resistance" = 16,
    "generic.luck" = 17,
    "generic.max_absorption" = 18,
    "generic.max_health" = 19,
    "generic.movement_speed" = 20,
    "generic.safe_fall_distance" = 21,
    "generic.scale" = 22,
    "zombie.spawn_reinforcements" = 23,
    "generic.step_height" = 24,
    "submerged_mining_speed" = 25,
    "sweeping_damage_ratio" = 26,
    "tempt_range" = 27,
    "water_movement_efficiency" = 28,
    "waypoint_transmit_range" = 29,
    "waypoint_receive_range" = 30,
}

declare const enum packet_tracked_waypoint_operation {
    "track" = 0,
    "untrack" = 1,
    "update" = 2,
}

declare const enum packet_tracked_waypoint_waypoint_type {
    "empty" = 0,
    "vec3i" = 1,
    "chunk" = 2,
    "azimuth" = 3,
}

declare const enum packet_name_9 {
    "bundle_delimiter" = 0x00,
    "spawn_entity" = 0x01,
    "animation" = 0x02,
    "statistics" = 0x03,
    "acknowledge_player_digging" = 0x04,
    "block_break_animation" = 0x05,
    "tile_entity_data" = 0x06,
    "block_action" = 0x07,
    "block_change" = 0x08,
    "boss_bar" = 0x09,
    "difficulty" = 0x0a,
    "chunk_batch_finished" = 0x0b,
    "chunk_batch_start" = 0x0c,
    "chunk_biomes" = 0x0d,
    "clear_titles" = 0x0e,
    "tab_complete" = 0x0f,
    "declare_commands" = 0x10,
    "close_window" = 0x11,
    "window_items" = 0x12,
    "craft_progress_bar" = 0x13,
    "set_slot" = 0x14,
    "cookie_request" = 0x15,
    "set_cooldown" = 0x16,
    "chat_suggestions" = 0x17,
    "custom_payload" = 0x18,
    "damage_event" = 0x19,
    "debug_sample" = 0x1a,
    "hide_message" = 0x1b,
    "kick_disconnect" = 0x1c,
    "profileless_chat" = 0x1d,
    "entity_status" = 0x1e,
    "sync_entity_position" = 0x1f,
    "explosion" = 0x20,
    "unload_chunk" = 0x21,
    "game_state_change" = 0x22,
    "open_horse_window" = 0x23,
    "hurt_animation" = 0x24,
    "initialize_world_border" = 0x25,
    "keep_alive" = 0x26,
    "map_chunk" = 0x27,
    "world_event" = 0x28,
    "world_particles" = 0x29,
    "update_light" = 0x2a,
    "login" = 0x2b,
    "map" = 0x2c,
    "trade_list" = 0x2d,
    "rel_entity_move" = 0x2e,
    "entity_move_look" = 0x2f,
    "move_minecart" = 0x30,
    "entity_look" = 0x31,
    "vehicle_move" = 0x32,
    "open_book" = 0x33,
    "open_window" = 0x34,
    "open_sign_entity" = 0x35,
    "ping" = 0x36,
    "ping_response" = 0x37,
    "craft_recipe_response" = 0x38,
    "abilities" = 0x39,
    "player_chat" = 0x3a,
    "end_combat_event" = 0x3b,
    "enter_combat_event" = 0x3c,
    "death_combat_event" = 0x3d,
    "player_remove" = 0x3e,
    "player_info" = 0x3f,
    "face_player" = 0x40,
    "position" = 0x41,
    "player_rotation" = 0x42,
    "recipe_book_add" = 0x43,
    "recipe_book_remove" = 0x44,
    "recipe_book_settings" = 0x45,
    "entity_destroy" = 0x46,
    "remove_entity_effect" = 0x47,
    "reset_score" = 0x48,
    "remove_resource_pack" = 0x49,
    "add_resource_pack" = 0x4a,
    "respawn" = 0x4b,
    "entity_head_rotation" = 0x4c,
    "multi_block_change" = 0x4d,
    "select_advancement_tab" = 0x4e,
    "server_data" = 0x4f,
    "action_bar" = 0x50,
    "world_border_center" = 0x51,
    "world_border_lerp_size" = 0x52,
    "world_border_size" = 0x53,
    "world_border_warning_delay" = 0x54,
    "world_border_warning_reach" = 0x55,
    "camera" = 0x56,
    "update_view_position" = 0x57,
    "update_view_distance" = 0x58,
    "set_cursor_item" = 0x59,
    "spawn_position" = 0x5a,
    "scoreboard_display_objective" = 0x5b,
    "entity_metadata" = 0x5c,
    "attach_entity" = 0x5d,
    "entity_velocity" = 0x5e,
    "entity_equipment" = 0x5f,
    "experience" = 0x60,
    "update_health" = 0x61,
    "held_item_slot" = 0x62,
    "scoreboard_objective" = 0x63,
    "set_passengers" = 0x64,
    "set_player_inventory" = 0x65,
    "teams" = 0x66,
    "scoreboard_score" = 0x67,
    "simulation_distance" = 0x68,
    "set_title_subtitle" = 0x69,
    "update_time" = 0x6a,
    "set_title_text" = 0x6b,
    "set_title_time" = 0x6c,
    "entity_sound_effect" = 0x6d,
    "sound_effect" = 0x6e,
    "start_configuration" = 0x6f,
    "stop_sound" = 0x70,
    "store_cookie" = 0x71,
    "system_chat" = 0x72,
    "playerlist_header" = 0x73,
    "nbt_query_response" = 0x74,
    "collect" = 0x75,
    "entity_teleport" = 0x76,
    "test_instance_block_status" = 0x77,
    "set_ticking_state" = 0x78,
    "step_tick" = 0x79,
    "transfer" = 0x7a,
    "advancements" = 0x7b,
    "entity_update_attributes" = 0x7c,
    "entity_effect" = 0x7d,
    "declare_recipes" = 0x7e,
    "tags" = 0x7f,
    "set_projectile_power" = 0x80,
    "custom_report_details" = 0x81,
    "server_links" = 0x82,
    "tracked_waypoint" = 0x83,
    "clear_dialog" = 0x84,
    "show_dialog" = 0x85,
}

declare const enum packet_set_difficulty_newDifficulty {
    "peaceful" = 0,
    "easy" = 1,
    "normal" = 2,
    "hard" = 3,
}

declare const enum packet_change_gamemode_mode {
    "survival" = 0,
    "creative" = 1,
    "adventure" = 2,
    "spectator" = 3,
}

declare const enum MovementFlags_bitflags {
    onGround = 1 << 0,
    hasHorizontalCollision = 1 << 1,
}

declare const enum packet_entity_action_actionId {
    "leave_bed" = 0,
    "start_sprinting" = 1,
    "stop_sprinting" = 2,
    "start_horse_jump" = 3,
    "stop_horse_jump" = 4,
    "open_vehicle_inventory" = 5,
    "start_elytra_flying" = 6,
}

declare const enum packet_player_input_inputs_bitflags {
    forward = 1 << 0,
    backward = 1 << 1,
    left = 1 << 2,
    right = 1 << 3,
    jump = 1 << 4,
    shift = 1 << 5,
    sprint = 1 << 6,
}

declare const enum packet_update_structure_block_flags {
    "ignore_entities" = 0,
    "show_air" = 1,
    "show_bounding_box" = 2,
    "strict" = 3,
}

declare const enum packet_name_10 {
    "teleport_confirm" = 0x00,
    "query_block_nbt" = 0x01,
    "select_bundle_item" = 0x02,
    "set_difficulty" = 0x03,
    "change_gamemode" = 0x04,
    "message_acknowledgement" = 0x05,
    "chat_command" = 0x06,
    "chat_command_signed" = 0x07,
    "chat_message" = 0x08,
    "chat_session_update" = 0x09,
    "chunk_batch_received" = 0x0a,
    "client_command" = 0x0b,
    "tick_end" = 0x0c,
    "settings" = 0x0d,
    "tab_complete" = 0x0e,
    "configuration_acknowledged" = 0x0f,
    "enchant_item" = 0x10,
    "window_click" = 0x11,
    "close_window" = 0x12,
    "set_slot_state" = 0x13,
    "cookie_response" = 0x14,
    "custom_payload" = 0x15,
    "debug_sample_subscription" = 0x16,
    "edit_book" = 0x17,
    "query_entity_nbt" = 0x18,
    "use_entity" = 0x19,
    "generate_structure" = 0x1a,
    "keep_alive" = 0x1b,
    "lock_difficulty" = 0x1c,
    "position" = 0x1d,
    "position_look" = 0x1e,
    "look" = 0x1f,
    "flying" = 0x20,
    "vehicle_move" = 0x21,
    "steer_boat" = 0x22,
    "pick_item_from_block" = 0x23,
    "pick_item_from_entity" = 0x24,
    "ping_request" = 0x25,
    "craft_recipe_request" = 0x26,
    "abilities" = 0x27,
    "block_dig" = 0x28,
    "entity_action" = 0x29,
    "player_input" = 0x2a,
    "player_loaded" = 0x2b,
    "pong" = 0x2c,
    "recipe_book" = 0x2d,
    "displayed_recipe" = 0x2e,
    "name_item" = 0x2f,
    "resource_pack_receive" = 0x30,
    "advancement_tab" = 0x31,
    "select_trade" = 0x32,
    "set_beacon_effect" = 0x33,
    "held_item_slot" = 0x34,
    "update_command_block" = 0x35,
    "update_command_block_minecart" = 0x36,
    "set_creative_slot" = 0x37,
    "update_jigsaw_block" = 0x38,
    "update_structure_block" = 0x39,
    "set_test_block" = 0x3a,
    "update_sign" = 0x3b,
    "arm_animation" = 0x3c,
    "spectate" = 0x3d,
    "test_instance_block_action" = 0x3e,
    "block_place" = 0x3f,
    "use_item" = 0x40,
    "custom_click_action" = 0x41,
}

